import Head from 'next/head'
import BlogPostList from '../../components/BlogPostList'
import styles from '../../styles/Home.module.css'
import { BlogPostListProps, BlogPost } from '../../interfaces';




export default function Blog({posts}: BlogPostListProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <BlogPostList posts={posts} />
      
      
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await res.json();

  return {
      props : {
          posts : posts,
  
      }
  }

}
