import Head from "next/head";
import BlogPostList from "../../components/BlogPostList";
import styles from "../../styles/Home.module.css";
import { BlogPost, User } from "../../interfaces";

interface BlogPostListProps {
    posts: BlogPost[];
    users: User[];
}

export default function Blog({ posts, users }: BlogPostListProps) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BlogPostList posts={posts} users={users} />
        </div>
    );
}

export async function getStaticProps() {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts");
    const posts = await res.json();
    const resUsers = await fetch("https://jsonplaceholder.typicode.com/users");
    const users = await resUsers.json();

    return {
        props: {
            posts: posts,
            users: users,
        },
    };
}
